use serde::{Deserialize, Serialize};
use serde_json::Value;

pub const DEFAULT_BUNDLE_ID: &str = "dev.agent-copilot.native";
pub const LEGACY_BUNDLE_ID: &str = "dev.skills-copilot.native";
pub const SERVICE_PROTOCOL_VERSION: u32 = 1;
pub const SUPPORTED_METHODS: &[&str] = &[
    "app.version",
    "app.stateSnapshot",
    "service.status",
    "adapter.listCapabilities",
    "adapter.listDiagnostics",
    "evidence.previewMcpServers",
    "evidence.piWritableHarness",
    "analysis.scoreSkillQuality",
    "analysis.detectStaleDrift",
    "knowledge.search",
    "knowledge.groupSimilarSkills",
    "knowledge.buildCapabilityTaxonomy",
    "knowledge.buildLocalSkillMap",
    "workspace.checkReadiness",
    "remediation.plan",
    "remediation.previewDrafts",
    "remediation.previewImpact",
    "remediation.batchReview",
    "remediation.listHistory",
    "remediation.recordHistory",
    "remediation.deleteHistory",
    "task.checkReadiness",
    "task.rankSkillRoutes",
    "task.compareAgentReadiness",
    "task.buildCockpit",
    "task.listBenchmarks",
    "task.saveBenchmark",
    "task.deleteBenchmark",
    "task.evaluateBenchmarks",
    "task.saveRoutingBaseline",
    "task.detectRoutingRegression",
    "routing.accuracyDashboard",
    "skill.lifecycleTimeline",
    "session.previewLocalSessions",
    "session.reviewAgentSkillUse",
    "session.listSkillReviews",
    "session.deleteSkillReview",
    "trace.importLocal",
    "trace.listImports",
    "trace.deleteImport",
    "llm.status",
    "llm.listProviderProfiles",
    "llm.saveProviderProfile",
    "llm.deleteProviderProfile",
    "llm.testProviderConnection",
    "llm.previewPrompt",
    "llm.confirmPromptAndSend",
    "llm.listPromptRuns",
    "llm.providerObservability",
    "llm.listModelTaskMatches",
    "llm.recordModelTaskMatch",
    "llm.deleteModelTaskMatch",
    "llm.prepareAction",
    "llm.prepareSkillAnalysis",
    "cleanup.listQueue",
    "cleanup.planGuidedFlow",
    "cleanup.recordGuidedStep",
    "comparison.listCrossAgent",
    "report.exportLocal",
    "rules.listTuning",
    "rules.setSeverityOverride",
    "rules.clearSeverityOverride",
    "rules.setSuppression",
    "rules.clearSuppression",
    "batch.previewSkillToggles",
    "batch.applySkillToggles",
    "script.previewExecution",
    "script.execute",
    "skillManager.listTools",
    "skillManager.search",
    "skillManager.listInstalled",
    "skillManager.previewInstall",
    "skillManager.applyInstall",
    "skillManager.previewRemove",
    "skillManager.applyRemove",
    "skillManager.previewUpdate",
    "skillManager.applyUpdate",
    "skillManager.previewLocalCreate",
    "skillManager.applyLocalCreate",
    "skillManager.deleteLocal",
    "project.getContext",
    "project.setContext",
    "project.clearContext",
    "project.validateContext",
    "catalog.listSkills",
    "catalog.getSkill",
    "catalog.analysis",
    "catalog.listFindings",
    "catalog.listFindingTriage",
    "catalog.setFindingTriage",
    "catalog.clearFindingTriage",
    "catalog.listConflicts",
    "catalog.importSkill",
    "catalog.scanClaude",
    "catalog.scanAll",
    "skill.exportBundle",
    "skill.install",
    "skill.listEvents",
    "config.toggleSkill",
    "config.readAgentConfig",
    "config.readClaudeSettings",
    "config.saveClaudeSettings",
    "snapshot.list",
    "snapshot.listAgentConfig",
    "snapshot.previewRollback",
    "snapshot.rollback",
];

#[derive(Debug, Clone, Deserialize)]
pub struct ServiceRequest {
    pub id: Option<String>,
    pub method: String,
    #[serde(default)]
    pub params: Value,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServiceResponse {
    pub id: Option<String>,
    pub ok: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub result: Option<Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<ServiceErrorRecord>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServiceErrorRecord {
    pub code: String,
    pub message: String,
}
